# Run me by typing `mythx analyze` in the directory of the yml file! :)

ci: true
confirm: true
analyze:
    mode: quick
    async: true
    create-group: true
    solc: 0.8.7
    remappings:
        - "@openzeppelin=node_modules/@openzeppelin"
    targets:
        - contracts/SoulReaper.sol:SoulReaper
        - contracts/soulswap/SoulSwapPair.sol:SoulSwapPair
        - contracts/soulswap/SoulSwapFactory.sol:SoulSwapFactory
        - contracts/soulswap/SoulSwapERC20.sol:SoulSwapERC20
        - contracts/soulswap/SoulSwapRouter.sol:SoulSwapRouter
        - contracts/SoulPower.sol:SoulPower
        - contracts/SpellBound.sol:SpellBound
        - contracts/SoulSummoner.sol:SoulSummoner
        - contracts/governance/Timelock.sol:Timelock
        - contracts/Migrator.sol:Migrator
